---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 127.0.0.1
      ansible_user: vagrant
      ansible_port: 2222
      ansible_ssh_private_key_file: /home/stade/workdir/ansible/homework2/.vagrant/machines/default/virtualbox/private_key
